apiVersion: v1
kind: ReplicationController
metadata:
  name: akka-k8s-example
spec:
  replicas: 1
  selector:
    app: akka-k8s-example
  template:
    metadata:
      labels:
        app: akka-k8s-example
    spec:
      containers:
        - env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_NAME
              value: akka-k8s-example
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: seednode-config-example:latest
          imagePullPolicy: Never
          name: akka-k8s-example
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 2552
              name: seed
